#!/usr/bin/env python3
"""Pre-compress the web panel page into the firmware.

The panel is ~120 KB of HTML/JS held as one C++ raw string literal, and it was
being stored — and sent — uncompressed. It gzips to about 32% of that, which is
80 KB of flash on a build that had run out of room.

This runs as a PlatformIO pre-build action so the compressed copy can never go
stale: it is regenerated from web_multi_page.h on every build, and web_multi.cpp
includes ONLY the generated header. If both were included the raw string would
still be linked in and the saving would silently vanish.
"""
import gzip
import os
import re
import sys

SRC = "examples/multi_node/web_multi_page.h"
DST = "examples/multi_node/web_multi_page_gz.h"


def build(src=SRC, dst=DST):
    with open(src, "r", encoding="utf-8") as f:
        text = f.read()
    m = re.search(r'R"MWPG\((.*)\)MWPG"', text, re.S)
    if not m:
        raise SystemExit(f"{src}: could not find the R\"MWPG(...)MWPG\" page literal")
    raw = m.group(1).encode("utf-8")
    # mtime=0 so an unchanged page produces an identical file and does not
    # force a needless rebuild of everything that includes it.
    gz = gzip.compress(raw, 9, mtime=0)

    out = [
        "// GENERATED by tools/gzip_panel.py — do not edit.",
        "// Source of truth is web_multi_page.h; this is its gzipped form.",
        f"// {len(raw)} bytes -> {len(gz)} bytes ({len(gz) * 100.0 / len(raw):.1f}%)",
        "#pragma once",
        "#include <stdint.h>",
        f"static const unsigned MULTI_PAGE_GZ_LEN = {len(gz)};",
        f"static const unsigned MULTI_PAGE_RAW_LEN = {len(raw)};",
        "static const uint8_t MULTI_PAGE_GZ[] = {",
    ]
    for i in range(0, len(gz), 16):
        out.append("  " + ",".join(f"0x{b:02x}" for b in gz[i:i + 16]) + ",")
    out.append("};")
    body = "\n".join(out) + "\n"

    # only rewrite when the content actually changed, to keep incremental
    # builds incremental
    if os.path.exists(dst):
        with open(dst, "r", encoding="utf-8") as f:
            if f.read() == body:
                return len(raw), len(gz), False
    with open(dst, "w", encoding="utf-8") as f:
        f.write(body)
    return len(raw), len(gz), True


try:
    Import("env")  # noqa: F821  (PlatformIO injects this)
except NameError:
    if __name__ == "__main__":
        r, g, changed = build()
        print(f"panel {r} -> {g} bytes ({g * 100.0 / r:.1f}%)"
              f"{'' if changed else ' (unchanged)'}")
else:
    r, g, changed = build()
    print(f"gzip_panel: {r} -> {g} bytes ({g * 100.0 / r:.1f}%)"
          f"{'' if changed else ', unchanged'}")
